import express from 'express';
const {Router} = express;
import bodypolygoncontroller from '../controller/bodypolygon_controller.js';
const router = Router();
router.get('/all', bodypolygoncontroller.getAll);
router.post('/new', bodypolygoncontroller.addBodypolygon);
router.post('/newfromjson', bodypolygoncontroller.addBodypolygonFromJson);
router.delete('/delete/:id', bodypolygoncontroller.deletebodypolygonbyid);
router.get('/:id', bodypolygoncontroller.getbyID);
// router.put('/update/:id', bodypolygoncontroller.updatebodypolygon);
export default router;