import express from 'express';
const {Router} = express;
import bodypolygoncontroller from '../controller/bodypolygon_controller.js';
const router = Router();
router.get('/all', bodypolygoncontroller.getAll);
router.get('/getbyID/:id', bodypolygoncontroller.getBodyPolygonById);
router.post('/new', bodypolygoncontroller.addBodypolygon);
router.put('/update/:id', bodypolygoncontroller.update);
router.post('/newfromjson', bodypolygoncontroller.addBodypolygonFromJson);
router.delete('/delete/:id', bodypolygoncontroller.deletebodypolygonbyid);
export default router;